"use client";

import {
  Apple,
  Banknote,
  Beaker,
  Bird,
  BookOpen,
  Brain,
  Briefcase,
  Building,
  Building2,
  CalendarDays,
  Calculator,
  Camera,
  Car,
  ChefHat,
  ClipboardList,
  Clock3,
  Coins,
  Cross,
  Dumbbell,
  Dna,
  Fish,
  FlaskRound,
  Flower2,
  FolderKanban,
  Gamepad2,
  Goal,
  Globe,
  GraduationCap,
  Handshake,
  HardHat,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Lightbulb,
  Mail,
  Theater,
  MoonStar,
  Mountain,
  Music,
  Newspaper,
  Palette,
  Palmtree,
  PartyPopper,
  PawPrint,
  PenLine,
  Pencil,
  Plane,
  Pill,
  Puzzle,
  Receipt,
  Rocket,
  Scale,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  Siren,
  Smile,
  Smartphone,
  Sprout,
  Stethoscope,
  Sun,
  Target,
  Telescope,
  Train,
  Trees,
  TrendingUp,
  Trophy,
  Users,
  Utensils,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import Image from "next/image";
import { cn } from "@/lib/utils";

interface LogoBadgeProps {
  logo?: string | null;
  fallback?: string;
  size?: "sm" | "md" | "lg";
  tone?: "primary" | "orange" | "muted";
  className?: string;
}

const SIZE_STYLES = {
  sm: {
    container: "h-8 w-8 rounded-lg",
    text: "text-lg",
  },
  md: {
    container: "h-10 w-10 rounded-xl",
    text: "text-xl",
  },
  lg: {
    container: "h-14 w-14 rounded-xl",
    text: "text-3xl",
  },
} as const;

const TONE_STYLES = {
  primary: "bg-primary-50 border-primary-100 text-primary-600",
  orange: "bg-orange-50 border-orange-100 text-orange-600",
  muted: "bg-gray-50 border-gray-200 text-gray-500",
} as const;

const ICON_SIZE_STYLES = {
  sm: "w-4 h-4",
  md: "w-5 h-5",
  lg: "w-7 h-7",
} as const;

const ICON_SIZE_PX = {
  sm: 16,
  md: 20,
  lg: 28,
} as const;

const ICON_TO_CUSTOM_ASSET: Record<string, string> = {
  "icon:graduation-cap": "education",
  "icon:pencil": "school",
  "icon:book-open": "book",
  "icon:pen": "school",
  "icon:languages": "language",
  "icon:calculator": "school",
  "icon:flask-round": "science",
  "icon:landmark": "education",
  "icon:globe": "nature",
  "icon:palette": "book",
  "icon:music": "communication",
  "icon:brain": "health",
  "icon:settings": "technology",
  "icon:laptop": "technology",
  "icon:chart-column": "business",
  "icon:trending-up": "business",
  "icon:hard-hat": "technology",
  "icon:zap": "science",
  "icon:beaker": "science",
  "icon:heart-pulse": "health",
  "icon:armchair": "body",
  "icon:smile": "body",
  "icon:cross": "health",
  "icon:stethoscope": "health",
  "icon:pill": "health",
  "icon:scale": "business",
  "icon:briefcase": "business",
  "icon:coins": "business",
  "icon:receipt": "business",
  "icon:rocket": "technology",
  "icon:newspaper": "communication",
  "icon:target": "sports",
  "icon:camera": "communication",
  "icon:film": "communication",
  "icon:dna": "science",
  "icon:telescope": "science",
  "icon:stars": "nature",
  "icon:leaf": "nature",
  "icon:bird": "animals",
  "icon:paw-print": "animals",
  "icon:shield": "animals",
  "icon:fish": "animals",
  "icon:waves": "nature",
  "icon:sun": "nature",
  "icon:mountain": "nature",
  "icon:apple": "food",
  "icon:utensils": "food",
  "icon:chef-hat": "food",
  "icon:plane": "travel",
  "icon:building": "home",
  "icon:train": "travel",
  "icon:car": "travel",
  "icon:shopping-bag": "business",
  "icon:shirt": "home",
  "icon:house": "home",
  "icon:calendar-days": "business",
  "icon:dumbbell": "sports",
  "icon:goal": "sports",
  "icon:circle": "sports",
  "icon:gamepad-2": "communication",
  "icon:party-popper": "communication",
  "icon:users": "communication",
  "icon:heart": "health",
  "icon:masks": "communication",
  "icon:smartphone": "communication",
  "icon:mail": "communication",
  "icon:clipboard-list": "business",
  "icon:handshake": "business",
  "icon:folder-kanban": "business",
  "icon:flower-2": "nature",
  "icon:moon-star": "nature",
  "icon:building-2": "home",
  "icon:sprout": "nature",
  "icon:palmtree": "travel",
  "icon:trees": "nature",
  "icon:siren": "health",
  "icon:clock-3": "business",
  "icon:banknote": "business",
  "icon:file-pen-line": "school",
  "icon:wrench": "technology",
  "icon:trophy": "sports",
  "icon:puzzle": "education",
  "icon:lightbulb": "education",
};

const APP_ICON_MAP: Record<string, LucideIcon> = {
  "icon:graduation-cap": GraduationCap,
  "icon:pencil": Pencil,
  "icon:book-open": BookOpen,
  "icon:pen": PenLine,
  "icon:languages": Languages,
  "icon:calculator": Calculator,
  "icon:flask-round": FlaskRound,
  "icon:landmark": Landmark,
  "icon:globe": Globe,
  "icon:palette": Palette,
  "icon:music": Music,
  "icon:brain": Brain,
  "icon:settings": Settings,
  "icon:laptop": Laptop,
  "icon:chart-column": TrendingUp,
  "icon:trending-up": TrendingUp,
  "icon:hard-hat": HardHat,
  "icon:zap": Zap,
  "icon:beaker": Beaker,
  "icon:heart-pulse": HeartPulse,
  "icon:armchair": Dumbbell,
  "icon:smile": Smile,
  "icon:cross": Cross,
  "icon:stethoscope": Stethoscope,
  "icon:pill": Pill,
  "icon:scale": Scale,
  "icon:briefcase": Briefcase,
  "icon:coins": Coins,
  "icon:receipt": Receipt,
  "icon:rocket": Rocket,
  "icon:newspaper": Newspaper,
  "icon:target": Target,
  "icon:camera": Camera,
  "icon:film": Theater,
  "icon:dna": Dna,
  "icon:telescope": Telescope,
  "icon:stars": MoonStar,
  "icon:leaf": Leaf,
  "icon:bird": Bird,
  "icon:paw-print": PawPrint,
  "icon:shield": Shield,
  "icon:fish": Fish,
  "icon:waves": Waves,
  "icon:sun": Sun,
  "icon:mountain": Mountain,
  "icon:apple": Apple,
  "icon:utensils": Utensils,
  "icon:chef-hat": ChefHat,
  "icon:plane": Plane,
  "icon:building": Building,
  "icon:train": Train,
  "icon:car": Car,
  "icon:shopping-bag": ShoppingBag,
  "icon:shirt": Shirt,
  "icon:house": House,
  "icon:calendar-days": CalendarDays,
  "icon:dumbbell": Dumbbell,
  "icon:goal": Goal,
  "icon:circle": Target,
  "icon:gamepad-2": Gamepad2,
  "icon:party-popper": PartyPopper,
  "icon:users": Users,
  "icon:heart": Heart,
  "icon:masks": Theater,
  "icon:smartphone": Smartphone,
  "icon:mail": Mail,
  "icon:clipboard-list": ClipboardList,
  "icon:handshake": Handshake,
  "icon:folder-kanban": FolderKanban,
  "icon:flower-2": Flower2,
  "icon:moon-star": MoonStar,
  "icon:building-2": Building2,
  "icon:sprout": Sprout,
  "icon:palmtree": Palmtree,
  "icon:trees": Trees,
  "icon:siren": Siren,
  "icon:clock-3": Clock3,
  "icon:banknote": Banknote,
  "icon:file-pen-line": PenLine,
  "icon:wrench": Wrench,
  "icon:trophy": Trophy,
  "icon:puzzle": Puzzle,
  "icon:lightbulb": Lightbulb,
};

export function LogoBadge({
  logo,
  fallback = "📘",
  size = "md",
  tone = "primary",
  className,
}: LogoBadgeProps) {
  const customAsset = logo ? ICON_TO_CUSTOM_ASSET[logo] : undefined;
  const Icon = logo ? APP_ICON_MAP[logo] : undefined;
  return (
    <div
      className={cn(
        "inline-flex items-center justify-center flex-shrink-0 border ring-1 ring-black/5 shadow-sm",
        SIZE_STYLES[size].container,
        TONE_STYLES[tone],
        className
      )}
    >
      {customAsset ? (
        <Image
          src={`/icons/topics/${customAsset}.svg`}
          alt=""
          aria-hidden
          unoptimized
          width={ICON_SIZE_PX[size]}
          height={ICON_SIZE_PX[size]}
          className={ICON_SIZE_STYLES[size]}
        />
      ) : Icon ? (
        <Icon className={ICON_SIZE_STYLES[size]} />
      ) : (
        <span className={cn("leading-none", SIZE_STYLES[size].text)}>
          {logo || fallback}
        </span>
      )}
    </div>
  );
}
